config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'  # щоб не писати на головній сторінці шлях /questions
  resources:questions
                                    # post '/questions', to: 'questions#create'
                                    # patch '/questions/:id', to: 'questions#update'
                                    # delete '/questions/:id', to: 'questions#destroy'
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :questions
    validates :name, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :questions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: %i[update show destroy edit]


  def create
    @category = Category.create(category_params)

    redirect_to categories_path, notice: 'Нова категорія створена'
  end

  def update
    @category.update(category_params)

    redirect_to categories_path, notice: 'Категорія збережена'
  end

  def destroy
    @category.destroy

    redirect_to categories_path, notice: 'Категорія видалена'
  end

  def  show
  end

  def index
    # @category = Category.new
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[update show destroy edit]   # before_action викликає метод set_question із приватних методів перед методами []
  # before_action :authenticate_user!, :only => [:create, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :owner, only: %i[update destroy edit]

  def create
    @question = current_user.questions.build(question_params)
    @question.save
    # @question = Question.create(question_params)
    
                                                    # @question = Question.create(body: params[:question][:body], 
                                                    #                          user_id: params[:user][:current_user.id])
                                                                                      # або
                                                                                      # @question = Question.create(params[:questions]) 

    redirect_to question_path(@question), notice: 'Нове питання створено'    # notice: це флеш, далі у layout
  end

  def update
    @question.update(question_params)
                                         # @question = Question.find(params[id:])
                                         # @question.update(
                                            # body: params[:question][:body], 
                                            # user_id: params[:question][:user_id]
                                            # )

    redirect_to question_path(@question), notice: 'Запитання збережено'
  end

  def destroy
    @question.destroy
                                        # @question = Question.find(params[id:])
                                        # @question.destroy

    redirect_to questions_path, notice: 'Запитання видалено'
  end

  def  show
                                        # @question = Question.find(params[id:])
  end

  def index
    # @question = current_user.questions.build
    @question = Question.new
    @questions = Question.all.includes(:category, :user)
  
  end

  def new
    #  @question = current_user.questions.build
    @question = Question.new
  end

  def edit
                                      # @question = Question.find(params[id:])
  end

  private

  def owner
    # @question = current_user.questions.find_by(params[:id])  # працює некорректно, завжди відкриває перше створене запитання
    @question = current_user.questions.where(id: params[:id]).first
    redirect_to questions_path, notice: 'У вас немає дозволу для зміни цього запитання' if @question.nil?
  end

  def question_params
    params.require(:question).permit(:body, :category_id)
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, many)

    case count % 10
    when 1..4 then one
    else
      many
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/categories/_form.html.erb
  <%= form_with model: category do |form|%>
    <p><%= form.label :name, "Назва категоріЇ" %> </p>
    <p><%= form.text_field :name, class: 'form-text-field' %></p>    

    <p class="mt"><%= form.submit "Зберегти", class: 'button button-main' %></p>
  <% end %>

app/views/categories/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Редактувати категорію <%= @category.id %></h2>

    <%= render 'form', category: @category %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <p class="mt">
    <%= link_to "Створити нову категорію", new_category_path, class: 'button button-main' %>
  </p>
</div>

  <% @categories.each do |category| %>
    <div class="mt-sm container">

    <div class="mb-sm">
      ID категорії: <%= category.id %>
    </div>

<div class="mb-sm">
  <%= category.name %>
</div>

<div class="text-sm question-footer">
  <div class="text-grey">
    <%= l(category.created_at, format: :short) %>
  </div>

  <div>
    <%= link_to fa_icon('pencil'), edit_category_path(category), title: 'Змінити назву категорії' %>
    <%= button_to fa_icon('trash-o'), category_path(category), method: :delete, title: 'Видалити категорію' %>
  </div>
</div> 
      <%= link_to "Відкрити", category_path(category) %>
    </div>
  <% end %>

  <div>
  <p class="mt">
    <%= link_to "Всі питання", questions_path, class: 'button button-main' %>
  </p>
</div>

app/views/categories/new.html.erb
<div class="container">
  <h2 class="title-lg mb">Нова категорія</h2>

  <%= render 'form', category: @category %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Категорія <%= @category.id %> </h2>

<div class="mb-sm">
  <%= @category.name %>
</div>

<div class="text-sm question-footer">
  <div class="text-grey">
    <%= l(@category.created_at, format: :short) %>
  </div>

  <div>
    <%= link_to fa_icon('pencil'), edit_category_path(@category), title: 'Змінити назву категорії' %>
    <%= button_to fa_icon('trash-o'), category_path(@category), method: :delete, title: 'Видалити категорію' %>
  </div>

  <p class="mt"><%= link_to "Всі категорії", categories_path %></p>
</div>

  <% @category.questions.each do |question| %>
    <div class="mt-sm container">
      <%= render question %>
      <%= link_to "Відкрити", question_path(question) %>
    </div>
  <% end %>

app/views/layouts/_auth_header.html.erb
<% if user_signed_in? %>
        <a href="#" class="button"> 
            Ласкаво просимо, <%= current_user.email %> Ваш ID:<%= current_user.id %>
        </a>
        <%= button_to "Вихід", destroy_user_session_path, method: :delete, class: "button" %>
        <%= link_to "Редагувати", edit_user_registration_path, class: "button" %>
<% else %>
    <%= link_to "Вхід", user_session_path, class: "button" %>

    <%= link_to "Реєстрація", new_user_registration_path, class: "button" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div class="wrapper">
    <!--devise-->
      <%= render '/layouts/auth_header' %>
    <!--devise-->
    <% if flash[:notice].present? %>
      <p class="mb mt message message-notice"><%= flash[:notice] %></p>
    <% end %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
  <%= form_with model: question do |form|%>
    <p><%= form.label :body, "Текст питання" %> </p>
    <p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>

    <p><%= form.label :category_id, "ID категорії" %> </p>
    <p><%= form.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true }, class: 'form-text-area' %></p>

    <%# <p class="mt"><%= form.label :user_id %></p>
    <%# <p><%= form.hidden_field :user_id, value: current_user.id %>
    

    <p class="mt"><%= form.submit "Зберегти", class: 'button button-main' %></p>
  <% end %>

app/views/questions/_question.html.erb
<div class="mb-sm">
  <%= question.user.email %>
</div>

<div class="mb-sm">
  ID: <%= question.user.id %>
</div>

<div class="mb-sm">
  <%= question.body %>
</div>

<div class="text-sm question-footer">
  <div class="text-grey">
    <%= l(question.created_at, format: :short) %>
  </div>

  <div>
  
  <%# <% if question.user.email == current_user.email якщо розлогінитись  - видає помилку undefined method `email' for nil:NilClass %>
    <% if question.user == current_user %>
    <%= link_to fa_icon('pencil'), edit_question_path(question), title: 'Змінити запитання' %>
    <%= button_to fa_icon('trash-o'), question_path(question), method: :delete, title: 'Видалити запитання' %>
    <% end %>
  </div>
</div> 

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Редактувати запитання <%= @question.id %></h2>

    <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="container">
  <p class="mt">
    <%= link_to "Створити нове питання", new_question_path, class: 'button button-main' %>
    <%= link_to "Створити нову категорію", new_category_path, class: 'button button-main' %>
    <%= link_to "Всі категорії", categories_path, class: 'button button-main' %>
  </p>

  <p class="mt">
    <%= render 'form', question: @question %>
  </p>
</div>

<div class="container mt-sm">
  <h2 class="title-lg">
    <%= @questions.count %>
    <%= inclination(@questions.count, 'запитання', 'запитань') %>
  </h2>
</div>

  <% @questions.each do |question| %>
    <div class="mt-sm container">
      <% if question.category.present? %>
        <div class="mb-sm">
          <%= link_to question.category.name, question.category %>
        </div>
      <% end %>
      <%= render question %>
      <%= link_to "Відкрити", question_path(question) %>
    </div>
  <% end %>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb">Нове питання</h2>

  <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Питання <%= @question.id %> </h2>
      <% if @question.category.present? %>
        <div class="mb-sm">
          <%= link_to @question.category.name, @question.category %>
        </div>
      <% end %>
  <%= render 'question', question: @question %>

  <p class="mt"><%= link_to "Всі питання", questions_path %></p>
</div>